"""
MQTT CONFIGURATION
"""

# MQTT defaults
MQTT_DEFAULT_PORT = 1883
MQTT_KEEPALIVE = 60
MQTT_CONNECT_TIMEOUT = 5
MQTT_QOS_AT_MOST_ONCE = 0
MQTT_QOS_AT_LEAST_ONCE = 1
MQTT_QOS_EXACTLY_ONCE = 2
MQTT_CONNECTED = 0

# TOPIC
SENSOR_TOPIC_BASE = "sensor/{serial}/{type}"
